<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="E5530-2340" name="com.test1.tests.RTestChrome" tests="25" failures="4" timestamp="20 Jul 2016 12:23:13 GMT" time="1068.104" errors="0">
  <testcase name="testSuccessfulNewClientCreationDBcheck" time="32.299" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulAddAttachmentDBcheck" time="41.776" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulImportFileToClient" time="41.692" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulNewUserCreate" time="38.678" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulSumSheetDownLoadFiref" time="20.616" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulNewAdminUserCreationDBcheck" time="42.419" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulAddSaleDates" time="227.652" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulNewClientCreationDBcheck" time="30.596" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulAddAttachmentDBcheck" time="41.860" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulLogIn" time="13.906" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulNewUserCreate" time="38.995" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulNewUserCreationDBcheck" time="34.861" classname="com.test1.tests.RTestChrome">
    <failure type="java.lang.AssertionError" message="The account for NewAdminUserD2 has not been successfully created. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The account for NewAdminUserD2 has not been successfully created. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.test1.tests.RTestChrome.testSuccessfulNewUserCreationDBcheck(RTestChrome.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- testSuccessfulNewUserCreationDBcheck -->
  <testcase name="testSuccessfulAdminAddAttachment" time="56.976" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulAdminAddAttachment" time="54.131" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulAdminAddAttachment" time="54.421" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulLogIn" time="13.309" classname="com.test1.tests.RTestChrome">
    <failure type="java.lang.AssertionError" message="Login is not successful for username NewParaUserD3 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login is not successful for username NewParaUserD3 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.test1.tests.RTestChrome.testSuccessfulLogIn(RTestChrome.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- testSuccessfulLogIn -->
  <testcase name="testSuccessfulNewClientCreation" time="33.599" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulAdminAddAttachment" time="54.262" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulNewUserCreationDBcheck" time="35.213" classname="com.test1.tests.RTestChrome">
    <failure type="java.lang.AssertionError" message="The account for NewParaUserD2 has not been successfully created. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The account for NewParaUserD2 has not been successfully created. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.test1.tests.RTestChrome.testSuccessfulNewUserCreationDBcheck(RTestChrome.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- testSuccessfulNewUserCreationDBcheck -->
  <testcase name="testSuccessfulAddAttachmentDBcheck" time="41.969" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulLogOut" time="16.548" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulImportFileToClient" time="42.734" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulLogIn" time="13.966" classname="com.test1.tests.RTestChrome"/>
  <testcase name="testSuccessfulLogIn" time="13.294" classname="com.test1.tests.RTestChrome">
    <failure type="java.lang.AssertionError" message="Login is not successful for username NewAdminUserD3 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login is not successful for username NewAdminUserD3 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.test1.tests.RTestChrome.testSuccessfulLogIn(RTestChrome.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- testSuccessfulLogIn -->
  <testcase name="testSuccessfulNewClientCreation" time="32.332" classname="com.test1.tests.RTestChrome"/>
</testsuite> <!-- com.test1.tests.RTestChrome -->
